import { getCosLaunchCapabilityStatus } from "@/lib/cos/launch-capabilities"
import type { CosCapabilityId } from "@/lib/cos/types"
type Item = { id: string; label: string; capabilityId?: CosCapabilityId }; type Group = { id: string; label: string; items: Item[] }
const groups: Group[] = [
  { id: "create", label: "Criar", items: [{ id: "form:client", label: "Cliente", capabilityId: "lead.create" }, { id: "form:property", label: "Imóvel", capabilityId: "property.create" }, { id: "form:proposal", label: "Proposta", capabilityId: "proposal.create" }, { id: "form:contract", label: "Contrato", capabilityId: "contract.create" }, { id: "form:agenda", label: "Compromisso", capabilityId: "agenda.create" }] },
  { id: "query", label: "Consultar", items: [{ id: "query:properties", label: "Imóveis", capabilityId: "property.search" }, { id: "query:clients", label: "Clientes", capabilityId: "lead.find" }, { id: "query:proposals", label: "Propostas", capabilityId: "proposal.summary" }, { id: "query:contracts", label: "Contratos", capabilityId: "contract.list" }, { id: "query:documents", label: "Documentos", capabilityId: "document.list" }, { id: "query:agenda", label: "Agenda de hoje", capabilityId: "agenda.today" }] },
  { id: "help", label: "Ajuda", items: [{ id: "help:properties", label: "Imóveis", capabilityId: "help.register_properties" }, { id: "help:clients", label: "Clientes", capabilityId: "help.manage_clients" }, { id: "help:proposals", label: "Propostas", capabilityId: "help.contracts_proposals" }, { id: "help:contracts", label: "Contratos", capabilityId: "help.contracts_proposals" }, { id: "help:studio", label: "Studio IA", capabilityId: "help.marketing_studio" }, { id: "help:catalog", label: "Catálogo", capabilityId: "help.general_question" }, { id: "help:marketplace", label: "Marketplace", capabilityId: "help.general_question" }, { id: "help:cos", label: "Como usar o COS", capabilityId: "help.use_cos" }] },
  { id: "attach", label: "Anexar", items: [{ id: "form:document", label: "Documento PDF", capabilityId: "lead.attach_document" }] },
]
export const cosLaunchMenuGroups = groups.map((group) => ({ ...group, items: group.items.filter((item) => !item.capabilityId || getCosLaunchCapabilityStatus(item.capabilityId) !== "NOT_AVAILABLE").map(({ capabilityId: _capabilityId, ...item }) => item) })).filter((group) => group.items.length)
