import "server-only"
import { executeCosLaunchAction } from "@/lib/cos-launch/actions"
import { buildCosLaunchForm } from "@/lib/cos-launch/forms"
import { getCosLaunchHelp } from "@/lib/cos-launch/help"
import { resolveCosLaunchIntent } from "@/lib/cos-launch/intent"
import { routeGuidedCosLaunchQuery } from "@/lib/cos-launch/queries"
import type { CosLaunchFormKind, CosLaunchIntent, CosLaunchRequest, CosLaunchResponse } from "@/lib/cos-launch/types"

const formByIntent: Partial<Record<CosLaunchIntent, CosLaunchFormKind>> = { create_property: "property", create_client: "client", create_contract: "contract", create_proposal: "proposal", create_agenda: "agenda", attach_document: "document", create_financial_income: "financial_income", create_financial_expense: "financial_expense", create_financial_commission: "financial_commission" }
async function query(intent: CosLaunchIntent, brokerId: string): Promise<CosLaunchResponse | null> { const actionByIntent: Partial<Record<CosLaunchIntent, string>> = { list_properties: "query:properties", list_clients: "query:clients", list_contracts: "query:contracts", list_proposals: "query:proposals", list_documents: "query:documents", agenda_today: "query:agenda", financial_summary: "query:finance", financial_receipts: "query:finance:receipts", financial_expenses: "query:finance:expenses", financial_commissions: "query:finance:commissions", financial_accounts: "query:finance:accounts", financial_upcoming: "query:finance:upcoming", financial_portfolio: "query:finance:portfolio" }; const action = actionByIntent[intent]; return action ? routeGuidedCosLaunchQuery(action, brokerId) : null }
function intentFromAction(action: string): CosLaunchIntent | null { const map: Record<string, CosLaunchIntent> = { "query:properties": "list_properties", "query:clients": "list_clients", "query:contracts": "list_contracts", "query:proposals": "list_proposals", "query:documents": "list_documents", "query:agenda": "agenda_today", "query:finance": "financial_summary", "query:finance:receipts": "financial_receipts", "query:finance:expenses": "financial_expenses", "query:finance:commissions": "financial_commissions", "query:finance:accounts": "financial_accounts", "query:finance:upcoming": "financial_upcoming", "query:finance:portfolio": "financial_portfolio", "form:property": "create_property", "form:client": "create_client", "form:contract": "create_contract", "form:proposal": "create_proposal", "form:agenda": "create_agenda", "form:document": "attach_document", "form:financial_income": "create_financial_income", "form:financial_expense": "create_financial_expense", "form:financial_commission": "create_financial_commission", "help:properties": "help_properties", "help:clients": "help_clients", "help:contracts": "help_contracts", "help:proposals": "help_proposals", "help:finance": "help_finance", "help:finance:portfolio": "help_finance_portfolio", "help:finance:entries": "help_finance_entries", "help:finance:commissions": "help_finance_commissions", "help:finance:accounts": "help_finance_accounts", "help:finance:rentals": "help_finance_rentals", "help:studio": "help_studio", "help:catalog": "help_catalog", "help:marketplace": "help_marketplace", "help:plan-account": "help_plan_account", "help:cos": "help_cos", "conversation:new": "new_conversation" }; return map[action] ?? null }

export async function routeCosLaunch(input: { brokerId: string; userId: string; request: CosLaunchRequest }): Promise<CosLaunchResponse> {
  const startedAt = Date.now(); const action = input.request.action?.trim() ?? ""
  if (action.startsWith("submit:")) { const kind = action.slice(7) as CosLaunchFormKind; const allowed: CosLaunchFormKind[] = ["property", "client", "proposal", "contract", "agenda", "document", "financial_income", "financial_expense", "financial_commission"]; if (!allowed.includes(kind)) return { message: "Esta ação não está disponível." }; const response = await executeCosLaunchAction({ kind, brokerId: input.brokerId, userId: input.userId, payload: input.request.payload ?? {} }); return { ...response, elapsedMs: Date.now() - startedAt } }
  const intent = intentFromAction(action) ?? resolveCosLaunchIntent(input.request.message ?? "")
  if (intent === "new_conversation") return { message: "Nova conversa iniciada.", elapsedMs: Date.now() - startedAt }
  const guided = action ? await routeGuidedCosLaunchQuery(action, input.brokerId) : null
  if (guided) return { ...guided, elapsedMs: Date.now() - startedAt }
  const found = await query(intent, input.brokerId); if (found) return { ...found, elapsedMs: Date.now() - startedAt }
  const kind = formByIntent[intent]; if (kind) return { message: "Preencha os campos abaixo para continuar.", form: await buildCosLaunchForm(input.brokerId, kind), elapsedMs: Date.now() - startedAt }
  return { ...getCosLaunchHelp(intent), elapsedMs: Date.now() - startedAt }
}
