CREATE TYPE "PropertyType" AS ENUM ('APARTMENT', 'HOUSE', 'COMMERCIAL');

ALTER TABLE "Property"
ADD COLUMN "description" TEXT,
ADD COLUMN "neighborhood" TEXT,
ADD COLUMN "bedrooms" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "bathrooms" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "parkingSpots" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "type" "PropertyType" NOT NULL DEFAULT 'APARTMENT',
ADD COLUMN "published" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "imageUrls" JSONB,
ADD COLUMN "viewsCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "leadsCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "Property"
SET
  "published" = CASE WHEN "status" = 'PUBLISHED' THEN true ELSE false END,
  "updatedAt" = "createdAt";
