ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "aiAssistantEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "aiMonthlyUsage" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Broker" ADD COLUMN IF NOT EXISTS "aiLastInteractionAt" TIMESTAMP(3);
