"use client"
import { useEffect, useState, type FormEvent } from "react"
import { ImagePlus, X } from "lucide-react"
import type { CosLaunchForm } from "@/lib/cos-launch/types"
type Props = { form: CosLaunchForm; busy: boolean; onCancel: () => void; onSubmit: (payload: Record<string, unknown>) => Promise<void> }
type Attachment = { id: string; name: string; type: string; size: number; category: "image" | "document"; dataUrl: string }
function readFile(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => typeof reader.result === "string" ? resolve(reader.result) : reject(new Error("Arquivo inválido")); reader.onerror = () => reject(reader.error ?? new Error("Falha ao ler arquivo")); reader.readAsDataURL(file) }) }
const inputClass = "min-h-11 w-full rounded-2xl border border-slate-200 bg-white/90 px-3 text-sm text-slate-900 outline-none transition focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100"
export function CosLaunchInlineForm({ form, busy, onCancel, onSubmit }: Props) {
  const [values, setValues] = useState<Record<string, string>>({ purpose: "Venda", type: "Apartamento", source: "COS", agendaType: "Compromisso" }); const [attachments, setAttachments] = useState<Attachment[]>([]); const [fileError, setFileError] = useState("")
  useEffect(() => { setValues({ purpose: "Venda", type: "Apartamento", source: "COS", agendaType: "Compromisso" }); setAttachments([]); setFileError("") }, [form.kind])
  const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }))
  const field = (label: string, key: string, options: { type?: string; required?: boolean; placeholder?: string } = {}) => <label className="grid gap-1.5 text-xs font-medium text-slate-600">{label}<input className={inputClass} type={options.type ?? "text"} required={options.required} placeholder={options.placeholder} value={values[key] ?? ""} onChange={(event) => set(key, event.target.value)} /></label>
  const select = (label: string, key: string, options: Array<{ id: string; label: string }>, required = false) => <label className="grid gap-1.5 text-xs font-medium text-slate-600">{label}<select className={inputClass} required={required} value={values[key] ?? ""} onChange={(event) => set(key, event.target.value)}><option value="">Selecione</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>
  async function handleFiles(files: FileList | null) { if (!files) return; setFileError(""); const selected = Array.from(files); const isProperty = form.kind === "property"; if (isProperty && attachments.length + selected.length > 8) return setFileError("Selecione no máximo 8 imagens."); if (selected.some((file) => isProperty ? !file.type.startsWith("image/") : file.type !== "application/pdf")) return setFileError(isProperty ? "Use apenas imagens." : "Use um arquivo PDF."); if (selected.some((file) => file.size > 8 * 1024 * 1024)) return setFileError("Cada arquivo pode ter no máximo 8 MB."); const loaded = await Promise.all(selected.map(async (file) => ({ id: crypto.randomUUID(), name: file.name, type: file.type, size: file.size, category: (isProperty ? "image" : "document") as Attachment["category"], dataUrl: await readFile(file) }))); setAttachments((current) => isProperty ? [...current, ...loaded] : loaded.slice(0, 1)) }
  async function submit(event: FormEvent) { event.preventDefault(); const payload: Record<string, unknown> = { ...values }; if (attachments.length) payload.attachments = attachments; if (form.kind === "document") payload.fileName = attachments[0]?.name ?? ""; await onSubmit(payload) }
  return <form onSubmit={submit} className="rounded-[28px] border border-emerald-100 bg-emerald-50/55 p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-start justify-between gap-4"><div><h3 className="font-semibold text-slate-950">{form.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{form.description}</p></div><button type="button" onClick={onCancel} className="grid size-9 shrink-0 place-items-center rounded-full border border-white bg-white text-slate-500" aria-label="Fechar formulário"><X className="size-4" /></button></div><div className="grid gap-3 sm:grid-cols-2">
    {form.kind === "client" ? <>{field("Nome", "name", { required: true })}{field("WhatsApp", "phone", { required: true, placeholder: "(00) 00000-0000" })}{field("E-mail", "email", { type: "email" })}{select("Origem", "source", [{ id: "COS", label: "COS" }, { id: "Manual", label: "Manual" }, { id: "Catalog", label: "Catálogo" }, { id: "Marketplace", label: "Marketplace" }])}{field("Interesse", "interest")}{select("Imóvel relacionado", "propertyId", form.properties ?? [])}</> : null}
    {form.kind === "property" ? <>{field("Título", "title", { required: true })}{select("Finalidade", "purpose", [{ id: "Venda", label: "Venda" }, { id: "Aluguel", label: "Aluguel" }], true)}{select("Tipo", "type", [{ id: "Apartamento", label: "Apartamento" }, { id: "Casa", label: "Casa" }, { id: "Sala Comercial", label: "Sala comercial" }, { id: "Terreno", label: "Terreno" }, { id: "Outro", label: "Outro" }], true)}{field("Preço", "price", { required: true, placeholder: "R$ 0,00" })}{field("Cidade", "city")}{field("Bairro", "neighborhood")}{field("Quartos", "bedrooms", { type: "number" })}{field("Banheiros", "bathrooms", { type: "number" })}{field("Vagas", "parkingSpots", { type: "number" })}{field("Metragem", "area", { type: "number" })}<label className="grid gap-1.5 text-xs font-medium text-slate-600 sm:col-span-2">Descrição<textarea className={`${inputClass} min-h-24 py-3`} value={values.description ?? ""} onChange={(event) => set("description", event.target.value)} /></label></> : null}
    {form.kind === "proposal" ? <>{select("Cliente", "leadId", form.clients ?? [], true)}{select("Imóvel", "propertyId", form.properties ?? [], true)}{field("Valor da proposta", "value", { required: true })}{field("Entrada", "entry")}{field("Parcelas", "installments", { type: "number" })}<label className="grid gap-1.5 text-xs font-medium text-slate-600 sm:col-span-2">Condições<textarea className={`${inputClass} min-h-20 py-3`} value={values.conditions ?? ""} onChange={(event) => set("conditions", event.target.value)} /></label></> : null}
    {form.kind === "contract" ? <>{field("Tipo de contrato", "contractType", { required: true, placeholder: "Ex.: Locação residencial" })}{select("Cliente", "leadId", form.clients ?? [], true)}{select("Imóvel", "propertyId", form.properties ?? [])}</> : null}
    {form.kind === "agenda" ? <>{field("Título", "title", { required: true })}{select("Tipo", "agendaType", [{ id: "Compromisso", label: "Compromisso" }, { id: "Visita", label: "Visita" }, { id: "Reunião", label: "Reunião" }, { id: "Lembrete", label: "Lembrete" }], true)}{field("Data", "date", { type: "date", required: true })}{field("Horário", "time", { type: "time", required: true })}{select("Cliente", "leadId", form.clients ?? [])}{select("Imóvel", "propertyId", form.properties ?? [])}</> : null}
    {form.kind === "document" ? <>{select("Cliente", "leadId", form.clients ?? [], true)}{field("Nome do documento", "documentName", { required: true })}{field("Tipo", "documentType", { placeholder: "Ex.: Identificação" })}</> : null}
  </div>{form.kind === "property" || form.kind === "document" ? <div className="mt-4"><label className="flex min-h-12 cursor-pointer items-center justify-center gap-2 rounded-2xl border border-dashed border-emerald-300 bg-white/80 px-4 text-sm font-medium text-emerald-800"><ImagePlus className="size-4" />{form.kind === "property" ? "Adicionar imagens" : "Selecionar PDF"}<input className="sr-only" type="file" accept={form.kind === "property" ? "image/*" : "application/pdf"} multiple={form.kind === "property"} onChange={(event) => void handleFiles(event.target.files)} /></label>{fileError ? <p className="mt-2 text-xs text-red-600">{fileError}</p> : null}{attachments.length ? <div className="mt-3 flex gap-2 overflow-x-auto pb-1">{attachments.map((attachment) => <div key={attachment.id} className="relative shrink-0">{attachment.category === "image" ? <img src={attachment.dataUrl} alt={attachment.name} className="size-20 rounded-xl object-cover" /> : <span className="flex h-12 max-w-56 items-center rounded-xl bg-white px-3 text-xs text-slate-600">{attachment.name}</span>}<button type="button" onClick={() => setAttachments((current) => current.filter((item) => item.id !== attachment.id))} className="absolute -right-1 -top-1 grid size-6 place-items-center rounded-full bg-slate-900 text-white" aria-label={`Remover ${attachment.name}`}><X className="size-3" /></button></div>)}</div> : null}</div> : null}<div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} className="min-h-11 rounded-full border border-slate-200 bg-white px-5 text-sm font-semibold text-slate-600">Cancelar</button><button type="submit" disabled={busy || (form.kind === "document" && attachments.length === 0)} className="min-h-11 rounded-full bg-emerald-950 px-6 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{busy ? "Processando..." : form.submitLabel}</button></div></form>
}
