import type { CosEntityModule } from "@/lib/cos/types"

export const agendaEntityModule: CosEntityModule = {
  entity: {
    id: "agenda",
    title: "Agenda",
    description: "Capacidades relacionadas a compromissos, lembretes e consultas de agenda.",
  },
  capabilities: [
    {
      descriptor: {
        id: "agenda.create",
        action: "CREATE_AGENDA_EVENT",
        title: "Compromisso criado",
        description: "Cria compromissos e lembretes na agenda do corretor.",
        domain: "agenda",
        entity: "agenda",
        aliases: ["agendar compromisso", "criar compromisso", "nova visita", "marque para", "marcar para amanha", "agendar para amanha"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: false,
        requiresSelection: false,
        inputContract: {
          required: ["time"],
          optional: ["date", "title", "type", "client", "property", "notes"],
        },
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso criar este compromisso agora na sua agenda. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "agenda.list",
        action: "LIST_AGENDA_EVENTS",
        title: "Consulta de agenda",
        description: "Lista compromissos pendentes ou filtrados por data.",
        domain: "agenda",
        entity: "agenda",
        aliases: ["meus compromissos", "agenda de hoje", "quais compromissos tenho hoje", "mostrar agenda"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "agenda.complete",
        action: "MARK_AGENDA_DONE",
        title: "Compromisso concluído",
        description: "Marca compromissos pendentes como concluídos.",
        domain: "agenda",
        entity: "agenda",
        aliases: ["concluir compromisso", "marcar compromisso como concluido"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "agenda.update",
        action: "UPDATE_AGENDA_EVENT",
        title: "Compromisso atualizado",
        description: "Atualiza data, horário, título ou observações de um compromisso.",
        domain: "agenda",
        entity: "agenda",
        aliases: ["atualizar compromisso", "editar compromisso", "remarcar compromisso"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: false,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso atualizar este compromisso agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "agenda.cancel",
        action: "CANCEL_AGENDA_EVENT",
        title: "Compromisso cancelado",
        description: "Cancela um compromisso da agenda mantendo o histórico.",
        domain: "agenda",
        entity: "agenda",
        aliases: ["cancelar compromisso", "cancelar visita", "desmarcar compromisso"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso cancelar este compromisso agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "agenda.today",
        action: "LIST_AGENDA_TODAY",
        title: "Agenda de hoje",
        description: "Lista os compromissos de hoje do corretor.",
        domain: "agenda",
        entity: "agenda",
        aliases: ["agenda de hoje", "compromissos de hoje", "o que tenho hoje"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "agenda.week",
        action: "LIST_AGENDA_WEEK",
        title: "Agenda da semana",
        description: "Lista os compromissos planejados para os próximos sete dias.",
        domain: "agenda",
        entity: "agenda",
        aliases: ["agenda da semana", "compromissos da semana", "minha semana"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "agenda.month",
        action: "LIST_AGENDA_MONTH",
        title: "Agenda do mês",
        description: "Lista os compromissos do mês atual com panorama operacional.",
        domain: "agenda",
        entity: "agenda",
        aliases: ["agenda do mes", "compromissos do mes", "minha agenda do mes"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
  ],
}
