import type { CosEntityModule } from "@/lib/cos/types"

export const catalogEntityModule: CosEntityModule = {
  entity: {
    id: "catalog",
    title: "Catálogo",
    description: "Capacidades relacionadas ao desempenho e leitura comercial do catálogo.",
  },
  capabilities: [
    {
      descriptor: {
        id: "analytics.summary",
        action: "getAnalyticsSummary",
        title: "Consulta de desempenho",
        description: "Resume analytics do catálogo e o desempenho comercial recente.",
        domain: "analytics",
        entity: "analytics",
        aliases: ["lead_ideas", "analytics do catalogo", "desempenho do catalogo"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "catalog.summary",
        action: "getCatalogSummary",
        title: "Resumo do catálogo",
        description: "Retorna um resumo sintético do catálogo publicado do corretor.",
        domain: "catalog",
        entity: "catalog",
        aliases: ["resumo do catalogo", "catalogo publicado"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "catalog.analyze",
        action: "analyzeCatalog",
        title: "Catálogo analisado",
        description: "Analisa o catálogo e retorna um panorama comercial resumido.",
        domain: "catalog",
        entity: "catalog",
        aliases: ["analyze_catalog", "create_catalog", "analise meu catalogo", "analisar catalogo"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
    {
      descriptor: {
        id: "catalog.publish",
        action: "PUBLISH_CATALOG",
        title: "Catalogo publicado",
        description: "Publica o imovel atual no catalogo compartilhavel do corretor.",
        domain: "catalog",
        entity: "catalog",
        aliases: ["publicar catalogo", "publique no catalogo", "colocar no catalogo"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso publicar este imovel no catalogo agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "catalog.unpublish",
        action: "UNPUBLISH_CATALOG",
        title: "Catalogo despublicado",
        description: "Remove um imovel do catalogo publico sem apagar o cadastro.",
        domain: "catalog",
        entity: "catalog",
        aliases: ["despublicar catalogo", "tirar do catalogo", "remover do catalogo"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso remover este imovel do catalogo agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "catalog.share",
        action: "SHARE_CATALOG",
        title: "Link do catalogo",
        description: "Gera o link publico oficial do catalogo para compartilhamento.",
        domain: "catalog",
        entity: "catalog",
        aliases: ["compartilhar catalogo", "link do catalogo", "copiar catalogo"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "catalog.stats",
        action: "CATALOG_STATS",
        title: "Estatisticas do catalogo",
        description: "Resume publicacao, visualizacoes e participacao comercial do catalogo.",
        domain: "catalog",
        entity: "catalog",
        aliases: ["estatisticas do catalogo", "stats do catalogo", "metricas do catalogo"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "analytics.performance",
        action: "GET_ANALYTICS_PERFORMANCE",
        title: "Performance comercial",
        description: "Resume a performance recente da operacao comercial e do catalogo.",
        domain: "analytics",
        entity: "analytics",
        aliases: ["performance", "performance comercial", "desempenho comercial"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "analytics.sales",
        action: "GET_ANALYTICS_SALES",
        title: "Analise de vendas",
        description: "Resume oportunidade, pipeline e ritmo comercial das vendas.",
        domain: "analytics",
        entity: "analytics",
        aliases: ["vendas", "analise de vendas", "pipeline de vendas"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "analytics.properties",
        action: "GET_ANALYTICS_PROPERTIES",
        title: "Analise de imoveis",
        description: "Resume distribuicao, publicacao e potencial da carteira de imoveis.",
        domain: "analytics",
        entity: "analytics",
        aliases: ["analise de imoveis", "performance dos imoveis", "carteira de imoveis"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "analytics.leads",
        action: "GET_ANALYTICS_LEADS",
        title: "Analise de leads",
        description: "Resume origem, ritmo e qualidade da base de clientes.",
        domain: "analytics",
        entity: "analytics",
        aliases: ["analise de leads", "performance dos leads", "qualidade dos clientes"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
  ],
}
