import type { CosEntityModule } from "@/lib/cos/types"

export const contractEntityModule: CosEntityModule = {
  entity: {
    id: "contract",
    title: "Contrato",
    description: "Capacidades relacionadas à geração, listagem e consulta de contratos.",
  },
  capabilities: [
    {
      descriptor: {
        id: "contract.create",
        action: "CREATE_CONTRACT",
        title: "Contrato gerado",
        description: "Cria contratos em rascunho vinculados a cliente e imóvel.",
        domain: "contract",
        entity: "contract",
        aliases: ["criar contrato", "gerar contrato", "contrato de compra e venda"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: false,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso gerar este contrato agora, salvar em Documentos e deixar como rascunho para revisão. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "contract.list",
        action: "LIST_CONTRACTS",
        title: "Consulta de contratos",
        description: "Lista contratos relacionados ao contexto consultado.",
        domain: "contract",
        entity: "contract",
        aliases: ["mostrar contratos", "meus contratos", "listar contratos"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "contract.get",
        action: "GET_CONTRACT",
        title: "Contrato consultado",
        description: "Abre ou resume o contrato mais relevante para o contexto consultado.",
        domain: "contract",
        entity: "contract",
        aliases: ["abrir contrato", "ver contrato", "enviar contrato"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "contract.preview",
        action: "CONTRACT_PREVIEW",
        title: "Preview de contrato",
        description: "Abre o preview operacional do contrato mais relevante para revisao.",
        domain: "contract",
        entity: "contract",
        aliases: ["preview do contrato", "prever contrato", "revisar contrato", "ver preview do contrato"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "contract.update",
        action: "UPDATE_CONTRACT",
        title: "Contrato atualizado",
        description: "Atualiza status, título ou observações operacionais do contrato selecionado.",
        domain: "contract",
        entity: "contract",
        aliases: ["atualizar contrato", "editar contrato", "ajustar contrato"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: false,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso atualizar este contrato agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "contract.send",
        action: "SEND_CONTRACT",
        title: "Contrato enviado",
        description: "Marca o contrato como enviado para assinatura ou revisao externa.",
        domain: "contract",
        entity: "contract",
        aliases: ["enviar contrato", "mandar contrato", "encaminhar contrato"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso enviar este contrato para assinatura agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "contract.sign",
        action: "SIGN_CONTRACT",
        title: "Contrato assinado",
        description: "Registra o contrato como assinado para concluir o fluxo operacional.",
        domain: "contract",
        entity: "contract",
        aliases: ["assinar contrato", "marcar contrato como assinado", "concluir assinatura"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso marcar este contrato como assinado agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "contract.cancel",
        action: "CANCEL_CONTRACT",
        title: "Contrato cancelado",
        description: "Cancela o contrato selecionado mantendo o histórico da negociação.",
        domain: "contract",
        entity: "contract",
        aliases: ["cancelar contrato", "cancelar assinatura", "encerrar contrato"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso cancelar este contrato agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "contract.download",
        action: "DOWNLOAD_CONTRACT",
        title: "Download de contrato",
        description: "Prepara os dados essenciais para exportação ou download do contrato.",
        domain: "contract",
        entity: "contract",
        aliases: ["baixar contrato", "download do contrato", "gerar pdf do contrato"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "contract.history",
        action: "CONTRACT_HISTORY",
        title: "Histórico de contratos",
        description: "Resume os contratos recentes e o andamento documental do corretor.",
        domain: "contract",
        entity: "contract",
        aliases: ["historico de contratos", "andamento dos contratos", "status dos contratos"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
  ],
}
