import type { CosEntityModule } from "@/lib/cos/types"

export const financeEntityModule: CosEntityModule = {
  entity: {
    id: "finance",
    title: "Financeiro",
    description: "Capacidades relacionadas à leitura financeira da carteira e operação.",
  },
  capabilities: [
    {
      descriptor: {
        id: "finance.summary",
        action: "getFinancialSummary",
        title: "Análise financeira",
        description: "Resume carteira, ticket médio e distribuição de imóveis ativos.",
        domain: "finance",
        entity: "financial",
        aliases: ["financeiro", "resumo financeiro", "comissao prevista", "quanto tenho de comissao"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.receivable",
        action: "GET_FINANCE_RECEIVABLE",
        title: "Recebiveis previstos",
        description: "Resume recebiveis previstos com base na carteira publicada e contratos ativos.",
        domain: "finance",
        entity: "financial",
        aliases: ["recebiveis", "contas a receber", "o que tenho para receber"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.payable",
        action: "GET_FINANCE_PAYABLE",
        title: "Contas a pagar",
        description: "Resume despesas e compromissos financeiros conhecidos da operacao.",
        domain: "finance",
        entity: "financial",
        aliases: ["contas a pagar", "despesas", "o que tenho para pagar"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.forecast",
        action: "GET_FINANCE_FORECAST",
        title: "Previsao financeira",
        description: "Gera uma leitura de previsao financeira da operacao com base na carteira.",
        domain: "finance",
        entity: "financial",
        aliases: ["previsao financeira", "forecast financeiro", "projecao financeira"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.commission",
        action: "GET_FINANCE_COMMISSION",
        title: "Comissao prevista",
        description: "Resume a comissao prevista ou potencial da carteira atual.",
        domain: "finance",
        entity: "financial",
        aliases: ["comissao prevista", "quanto tenho de comissao", "minha comissao"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.cashflow",
        action: "GET_FINANCE_CASHFLOW",
        title: "Fluxo de caixa",
        description: "Resume entradas e saidas operacionais em uma visao de caixa.",
        domain: "finance",
        entity: "financial",
        aliases: ["fluxo de caixa", "caixa", "cashflow"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
  ],
}
