import type { CosEntityModule } from "@/lib/cos/types"

export const financeEntityModule: CosEntityModule = {
  entity: {
    id: "finance",
    title: "Financeiro",
    description: "Capacidades relacionadas à leitura financeira da carteira e operação.",
  },
  capabilities: [
    {
      descriptor: {
        id: "finance.summary",
        action: "getFinancialSummary",
        title: "Análise financeira",
        description: "Resume carteira e movimentação financeira operacional do mês.",
        domain: "finance",
        entity: "financial",
        aliases: ["financeiro", "resumo financeiro", "valor da carteira", "qual o valor da minha carteira"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.receivable",
        action: "GET_FINANCE_RECEIVABLE",
        title: "Recebíveis previstos",
        description: "Resume lançamentos previstos e atrasados já registrados na operação.",
        domain: "finance",
        entity: "financial",
        aliases: ["recebiveis", "contas a receber", "o que tenho para receber", "quanto tenho a receber"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.payable",
        action: "GET_FINANCE_PAYABLE",
        title: "Contas a pagar",
        description: "Resume despesas e compromissos financeiros conhecidos da operação.",
        domain: "finance",
        entity: "financial",
        aliases: ["contas a pagar", "despesas", "o que tenho para pagar", "quanto gastei este mes", "quanto gastei no mes"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.forecast",
        action: "GET_FINANCE_FORECAST",
        title: "Previsão financeira",
        description: "Lista próximos recebimentos registrados em 7 e 30 dias e os atrasados.",
        domain: "finance",
        entity: "financial",
        aliases: ["previsao financeira", "proximos recebimentos", "quais sao meus proximos recebimentos", "recebimentos dos proximos 7 dias", "recebimentos dos proximos 30 dias"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.commission",
        action: "GET_FINANCE_COMMISSION",
        title: "Comissões",
        description: "Resume comissões registradas, recebidas, previstas e atrasadas.",
        domain: "finance",
        entity: "financial",
        aliases: ["comissao prevista", "quanto tenho de comissao", "minha comissao", "quais comissoes estao atrasadas", "comissoes atrasadas"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "finance.cashflow",
        action: "GET_FINANCE_CASHFLOW",
        title: "Fluxo de caixa",
        description: "Resume entradas e saídas operacionais em uma visão de caixa.",
        domain: "finance",
        entity: "financial",
        aliases: ["fluxo de caixa", "caixa", "cashflow", "quanto recebi este mes", "quanto recebi no mes", "resultado do mes"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
  ],
}
