import type { CosEntityModule } from "@/lib/cos/types"

export const generalEntityModule: CosEntityModule = {
  entity: {
    id: "general",
    title: "Geral",
    description: "Camada de atendimento geral e fallback conversacional do COS.",
  },
  capabilities: [
    {
      descriptor: {
        id: "general.chat",
        action: "general",
        title: "Atendimento geral",
        description: "Conduz a conversa geral do COS quando não há uma ação operacional específica.",
        domain: "general",
        entity: "conversation",
        aliases: ["chat", "chat_cos"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
    // As 7 capabilities de ajuda abaixo correspondem 1:1 aos botões da seção "Ajuda" do menu
    // "+" do COS (ver actionMap em components/broker-portal.tsx). O frontend envia o próprio id
    // do botão como requestedAction, que casa direto com o `action` de cada descriptor aqui —
    // isso pula inteiramente a cadeia de regex de inferAssessorAction() e o AI Orchestrator (ver
    // shouldTryAiOrchestrator/scoreCapability), então essas mensagens nunca mais correm o risco
    // de colidir com a regex de outra capability (era o que fazia "Como cadastrar imóveis no
    // EME?" cair em createPropertyDraft e tentar iniciar um cadastro de verdade).
    {
      descriptor: {
        id: "help.first_steps",
        action: "help_first_steps",
        title: "Ajuda: primeiros passos",
        description: "Explica como começar a usar o EME, usando o manual oficial do sistema como referência.",
        domain: "general",
        entity: "conversation",
        aliases: ["help_first_steps", "primeiros passos", "como comecar no eme"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
    {
      descriptor: {
        id: "help.use_cos",
        action: "help_use_cos",
        title: "Ajuda: como usar o COS",
        description: "Explica como usar o COS no dia a dia, usando o manual oficial do sistema como referência.",
        domain: "general",
        entity: "conversation",
        aliases: ["help_use_cos", "como usar o cos"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
    {
      descriptor: {
        id: "help.register_properties",
        action: "help_register_properties",
        title: "Ajuda: cadastrar imóveis",
        description: "Explica como cadastrar imóveis no EME, usando o manual oficial do sistema como referência.",
        domain: "general",
        entity: "conversation",
        aliases: ["help_register_properties", "como cadastrar imoveis"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
    {
      descriptor: {
        id: "help.manage_clients",
        action: "help_manage_clients",
        title: "Ajuda: gerenciar clientes",
        description: "Explica como gerenciar clientes no EME, usando o manual oficial do sistema como referência.",
        domain: "general",
        entity: "conversation",
        aliases: ["help_manage_clients", "como gerenciar clientes"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
    {
      descriptor: {
        id: "help.contracts_proposals",
        action: "help_contracts_proposals",
        title: "Ajuda: contratos e propostas",
        description: "Explica como funcionam contratos e propostas no EME, usando o manual oficial do sistema como referência.",
        domain: "general",
        entity: "conversation",
        aliases: ["help_contracts_proposals", "contratos e propostas"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
    {
      descriptor: {
        id: "help.marketing_studio",
        action: "help_marketing_studio",
        title: "Ajuda: marketing e Studio IA",
        description: "Explica o Studio IA e o marketing do EME, usando o manual oficial do sistema como referência.",
        domain: "general",
        entity: "conversation",
        aliases: ["help_marketing_studio", "studio ia e marketing"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
    {
      descriptor: {
        id: "help.general_question",
        action: "help_general_question",
        title: "Ajuda: dúvida geral",
        description: "Responde uma dúvida livre sobre o EME, usando o manual oficial completo do sistema como referência.",
        domain: "general",
        entity: "conversation",
        aliases: ["help_general_question", "tirar uma duvida"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
  ],
}
