import type { CosEntityModule } from "@/lib/cos/types"

export const leadEntityModule: CosEntityModule = {
  entity: {
    id: "lead",
    title: "Cliente (Lead)",
    description: "Capacidades relacionadas ao CRM, cadastro e análise de clientes/leads.",
  },
  capabilities: [
    {
      descriptor: {
        id: "lead.create",
        action: "createLead",
        title: "Cadastro de cliente",
        description: "Cria ou atualiza um lead/cliente a partir da conversa.",
        domain: "lead",
        entity: "lead",
        aliases: ["cadastrar cliente", "cadastrar lead", "novo cliente", "novo lead"],
        responseMode: "raw",
        source: "legacy",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso cadastrar ou atualizar este cliente agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "lead.summary",
        action: "getLeadsSummary",
        title: "Resumo de clientes",
        description: "Retorna um resumo operacional dos leads/clientes do corretor.",
        domain: "lead",
        entity: "lead",
        aliases: ["resumo de clientes", "resumo de leads", "analisar clientes"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "lead.summarize",
        action: "summarizeLead",
        title: "Análise de clientes",
        description: "Resume os últimos leads e atendimentos relevantes.",
        domain: "lead",
        entity: "lead",
        aliases: ["reply_client", "resumir lead", "analisar lead", "revisar clientes"],
        responseMode: "raw",
        source: "legacy",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "lead.update",
        action: "UPDATE_LEAD",
        title: "Cliente atualizado",
        description: "Atualiza dados operacionais do cliente ja existente.",
        domain: "lead",
        entity: "lead",
        aliases: ["atualizar cliente", "editar cliente", "ajustar cliente"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso atualizar este cliente agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "lead.delete",
        action: "DELETE_LEAD",
        title: "Cliente removido",
        description: "Arquiva ou remove o cliente selecionado da operacao.",
        domain: "lead",
        entity: "lead",
        aliases: ["apagar cliente", "excluir cliente", "deletar cliente"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso remover este cliente agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "lead.find",
        action: "FIND_LEAD",
        title: "Cliente encontrado",
        description: "Localiza clientes por nome, telefone, email ou contexto atual.",
        domain: "lead",
        entity: "lead",
        aliases: ["buscar cliente", "encontrar cliente", "localizar cliente"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "lead.timeline",
        action: "LEAD_TIMELINE",
        title: "Timeline do cliente",
        description: "Resume interacoes, compromissos e documentos ligados ao cliente.",
        domain: "lead",
        entity: "lead",
        aliases: ["timeline do cliente", "historico do cliente", "interacoes do cliente"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "lead.convert",
        action: "CONVERT_LEAD",
        title: "Cliente convertido",
        description: "Marca o cliente como convertido para negocio ganho.",
        domain: "lead",
        entity: "lead",
        aliases: ["converter cliente", "ganhei este cliente", "marcar cliente como ganho"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso marcar este cliente como convertido agora. Deseja confirmar?",
      },
    },
  ],
}
