import type { CosEntityModule } from "@/lib/cos/types"

export const propertyEntityModule: CosEntityModule = {
  entity: {
    id: "property",
    title: "Imóvel",
    description: "Capacidades relacionadas ao cadastro, busca e qualificação comercial de imóveis.",
  },
  capabilities: [
    {
      descriptor: {
        id: "property.create",
        action: "createPropertyDraft",
        title: "Cadastro de imóvel",
        description: "Cria um imóvel em rascunho a partir de instruções em linguagem natural.",
        domain: "property",
        entity: "property",
        aliases: ["create_ad", "cadastrar imovel", "criar imovel", "novo imovel", "anuncio do imovel"],
        responseMode: "raw",
        source: "legacy",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Encontrei um pedido para cadastrar um imóvel em rascunho. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "property.search",
        action: "searchProperties",
        title: "Busca de imóveis",
        description: "Pesquisa imóveis do corretor com base em filtros extraídos da mensagem.",
        domain: "property",
        entity: "property",
        aliases: [
          "match_properties",
          "search_property",
          "buscar imovel",
          "buscar apartamento",
          "buscar apartamentos",
          "busque apartamento",
          "busque apartamentos",
          "buscar casa",
          "buscar casas",
          "busque casa",
          "busque casas",
          "procurar imovel",
          "apartamento",
          "apartamentos",
          "casa",
          "casas",
          "terreno",
          "terrenos",
        ],
        responseMode: "raw",
        source: "legacy",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp", "demo"],
      },
    },
    {
      descriptor: {
        id: "property.description.improve",
        action: "improvePropertyDescription",
        title: "Melhoria de descrição",
        description: "Melhora a base de descrição comercial de um imóvel.",
        domain: "property",
        entity: "property",
        aliases: [
          "improve_description",
          "melhorar descricao",
          "melhore a descricao",
          "descricao do imovel",
          "gerar anuncio",
          "gere um anuncio",
          "criar anuncio",
        ],
        responseMode: "nlg",
        source: "legacy",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "property.publish",
        action: "PUBLISH_PROPERTY",
        title: "Imovel publicado",
        description: "Publica um imovel do workspace ou da selecao atual no catalogo.",
        domain: "property",
        entity: "property",
        aliases: ["publicar imovel", "publique este imovel", "anunciar imovel"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso publicar este imovel agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "property.unpublish",
        action: "UNPUBLISH_PROPERTY",
        title: "Imovel despublicado",
        description: "Remove o imovel do catalogo sem apagar o cadastro.",
        domain: "property",
        entity: "property",
        aliases: ["despublicar imovel", "tirar imovel do catalogo", "pausar imovel"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso tirar este imovel do catalogo agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "property.media.update",
        action: "UPDATE_PROPERTY_MEDIA",
        title: "Midias do imovel atualizadas",
        description: "Atualiza o conjunto de fotos ou midias do imovel selecionado.",
        domain: "property",
        entity: "property",
        aliases: ["atualizar fotos do imovel", "atualizar midias do imovel", "mudar fotos do imovel"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso atualizar as midias deste imovel agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "property.price.suggest",
        action: "SUGGEST_PROPERTY_PRICE",
        title: "Sugestao de preco",
        description: "Calcula uma sugestao operacional de preco com base na carteira do corretor.",
        domain: "property",
        entity: "property",
        aliases: ["sugerir preco", "sugestao de preco", "quanto vale este imovel"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "property.archive",
        action: "ARCHIVE_PROPERTY",
        title: "Imovel arquivado",
        description: "Arquiva o imovel e interrompe sua disponibilidade operacional.",
        domain: "property",
        entity: "property",
        aliases: ["arquivar imovel", "encerrar imovel", "remover imovel"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso arquivar este imovel agora. Deseja confirmar?",
      },
    },
  ],
}
