import type { CosEntityModule } from "@/lib/cos/types"

export const studioIaEntityModule: CosEntityModule = {
  entity: {
    id: "studio_ia",
    title: "Studio IA",
    description: "Capacidades relacionadas a geração, refinamento e reaproveitamento de campanhas do Studio IA.",
  },
  capabilities: [
    {
      descriptor: {
        id: "studio.generateDescription",
        action: "STUDIO_GENERATE_DESCRIPTION",
        title: "Descrição gerada",
        description: "Gera uma descrição comercial a partir do contexto do imóvel.",
        domain: "studio",
        entity: "studio",
        aliases: ["gerar descricao", "descricao com ia", "criar descricao com ia"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "studio.generateCampaign",
        action: "STUDIO_GENERATE_CAMPAIGN",
        title: "Campanha gerada",
        description: "Gera uma campanha base no Studio IA para o imóvel atual.",
        domain: "studio",
        entity: "studio",
        aliases: ["gerar campanha", "criar campanha", "campanha com ia"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso gerar esta campanha no Studio IA agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "studio.generateInstagram",
        action: "STUDIO_GENERATE_INSTAGRAM",
        title: "Campanha Instagram gerada",
        description: "Gera assets de Instagram para um imóvel ou campanha ativa.",
        domain: "studio",
        entity: "studio",
        aliases: ["gerar instagram", "campanha instagram", "post para instagram"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso gerar a campanha de Instagram agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "studio.generateFacebook",
        action: "STUDIO_GENERATE_FACEBOOK",
        title: "Campanha Facebook gerada",
        description: "Gera uma variação de campanha orientada a Facebook.",
        domain: "studio",
        entity: "studio",
        aliases: ["gerar facebook", "campanha facebook", "post para facebook"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso gerar a campanha de Facebook agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "studio.generateVideo",
        action: "STUDIO_GENERATE_VIDEO",
        title: "Vídeo gerado",
        description: "Gera um roteiro ou campanha de vídeo para o imóvel atual.",
        domain: "studio",
        entity: "studio",
        aliases: ["gerar video", "video com ia", "criar video"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso gerar este video agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "studio.generateStory",
        action: "STUDIO_GENERATE_STORY",
        title: "Story gerado",
        description: "Gera um asset de story para campanhas ou divulgação rápida.",
        domain: "studio",
        entity: "studio",
        aliases: ["gerar story", "story com ia", "criar story"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: true,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso gerar este story agora. Deseja confirmar?",
      },
    },
    {
      descriptor: {
        id: "studio.improveText",
        action: "STUDIO_IMPROVE_TEXT",
        title: "Texto refinado",
        description: "Refina textos e copys do Studio IA a partir do contexto atual.",
        domain: "studio",
        entity: "studio",
        aliases: ["melhorar texto", "refinar copy", "melhorar legenda"],
        responseMode: "raw",
        source: "modular",
        mutatesData: false,
        requiresConfirmation: false,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
      },
    },
    {
      descriptor: {
        id: "studio.regenerate",
        action: "STUDIO_REGENERATE",
        title: "Campanha regenerada",
        description: "Regenera a última campanha ou asset relevante do Studio IA.",
        domain: "studio",
        entity: "studio",
        aliases: ["regenerar campanha", "regenerar asset", "gerar novamente"],
        responseMode: "raw",
        source: "modular",
        mutatesData: true,
        requiresConfirmation: true,
        requiresSelection: false,
        surfaces: ["portal", "cos_home", "whatsapp"],
        confirmationMessage: "Posso regenerar este material agora. Deseja confirmar?",
      },
    },
  ],
}
