import type { AiOperationCatalogEntry } from "@/lib/ai-cost-contract"

const catalog: AiOperationCatalogEntry[] = [
  {
    id: "contracts.template_analysis",
    module: "Contratos",
    feature: "Importação de modelo próprio",
    capability: "contracts.template.extract",
    route: "/api/brokers/contract-templates",
    file: "lib/contract-template-analysis.server.ts",
    handler: "analyzeContractTemplate",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Extrai estrutura e campos variáveis sem reescrever o conteúdo jurídico original.",
    billableUnit: "document",
    avgInputTokens: 9000,
    avgOutputTokens: 2400,
    retryProfile: "rare",
    cacheable: true,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 2,
    expectedCadence: "low",
    suggestedCredits: 0,
    notes: "Análise única por hash de arquivo; não debita créditos EME nesta fase.",
  },
  {
    id: "cos.message",
    module: "COS",
    feature: "Conversa operacional",
    capability: "cos.message",
    route: "/api/assistant/eme",
    file: "app/api/assistant/eme/route.ts",
    handler: "POST",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Resposta operacional do COS para mensagens de portal/PWA.",
    billableUnit: "request",
    avgInputTokens: 1400,
    avgOutputTokens: 260,
    retryProfile: "rare",
    cacheable: false,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 240,
    expectedCadence: "high",
    currentCreditActionKey: "general",
    suggestedCredits: 1,
  },
  {
    id: "cos.ai_orchestrator",
    module: "COS",
    feature: "Planejamento por IA",
    capability: "cos.ai_orchestrator",
    route: "/api/assistant/eme",
    file: "lib/cos/ai-orchestrator.ts",
    handler: "generateCosAiExecutionPlan",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Planner estruturado via Responses API quando o fluxo deterministico nao resolve.",
    billableUnit: "request",
    avgInputTokens: 2100,
    avgOutputTokens: 220,
    retryProfile: "rare",
    cacheable: false,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 45,
    expectedCadence: "medium",
    suggestedCredits: 2,
  },
  {
    id: "cos.v2.interpretation",
    module: "COS",
    feature: "Interpretação conversacional V2",
    capability: "cos.v2.interpretation",
    route: "/api/assistant/eme",
    file: "lib/cos-v2/interpreter.ts",
    handler: "interpretCosV2Turn",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Interpreta linguagem livre em um contrato estruturado sem executar handlers.",
    billableUnit: "request",
    avgInputTokens: 1500,
    avgOutputTokens: 360,
    retryProfile: "rare",
    cacheable: false,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 240,
    expectedCadence: "high",
    suggestedCredits: 0,
  },
  {
    id: "cos.v2.response",
    module: "COS",
    feature: "Resposta natural V2",
    capability: "cos.v2.response",
    route: "/api/assistant/eme",
    file: "lib/cos-v2/response.ts",
    handler: "buildCosV2Answer",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Sintetiza respostas curtas a partir de fatos validados do Knowledge e do Registry.",
    billableUnit: "request",
    avgInputTokens: 700,
    avgOutputTokens: 150,
    retryProfile: "rare",
    cacheable: false,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 80,
    expectedCadence: "medium",
    suggestedCredits: 0,
  },
  {
    id: "property.generate_copy",
    module: "Imoveis",
    feature: "Cadastro inteligente",
    capability: "property.generate",
    route: "/api/ai/generate-property",
    file: "lib/property-ai.ts",
    handler: "generatePropertyCopy",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Gera descricao comercial, titulo e highlights do imovel.",
    billableUnit: "request",
    avgInputTokens: 900,
    avgOutputTokens: 180,
    retryProfile: "rare",
    cacheable: true,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 32,
    expectedCadence: "medium",
    currentCreditActionKey: "generate_property_ai",
    suggestedCredits: 2,
  },
  {
    id: "property.import_text",
    module: "Imoveis",
    feature: "Importacao por texto/link/XML URL",
    capability: "property.import.text",
    route: "/api/properties/import/ad/extract",
    file: "lib/property-ad-import.ts",
    handler: "extractPropertyFromAd",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Extrai PropertyDrafts a partir de texto, URL e pagina do anuncio.",
    billableUnit: "request",
    avgInputTokens: 2800,
    avgOutputTokens: 520,
    retryProfile: "moderate",
    cacheable: true,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 24,
    expectedCadence: "medium",
    currentCreditActionKey: "smart_import_text",
    suggestedCredits: 4,
  },
  {
    id: "property.import_image",
    module: "Imoveis",
    feature: "Importacao por imagem/print",
    capability: "property.import.image",
    route: "/api/properties/import/ad/extract",
    file: "lib/property-ad-import.ts",
    handler: "extractPropertyFromAd",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Extrai PropertyDrafts a partir de prints, imagens e OCR visual.",
    billableUnit: "request",
    avgInputTokens: 4200,
    avgOutputTokens: 650,
    avgImages: 1,
    retryProfile: "moderate",
    cacheable: true,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 18,
    expectedCadence: "medium",
    currentCreditActionKey: "smart_import_image",
    suggestedCredits: 5,
  },
  {
    id: "broker.assistant",
    module: "Corretor EME",
    feature: "Assistente transacional",
    capability: "broker.assistant",
    route: "/api/ai/broker-assistant",
    file: "lib/broker-assistant.ts",
    handler: "generateBrokerAssistantResponse",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Resposta assistida para canal operacional do corretor.",
    billableUnit: "request",
    avgInputTokens: 950,
    avgOutputTokens: 240,
    retryProfile: "rare",
    cacheable: false,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 80,
    expectedCadence: "medium",
    currentCreditActionKey: "create_ad",
    suggestedCredits: 1,
  },
  {
    id: "assessor.whatsapp.reply",
    module: "Assessor EME",
    feature: "Resposta comercial no WhatsApp",
    capability: "assessor.reply",
    route: "/api/whatsapp/webhook",
    file: "lib/eme-backend.ts",
    handler: "generateAssessorText",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Refina a resposta final do Assessor EME no WhatsApp.",
    billableUnit: "request",
    avgInputTokens: 650,
    avgOutputTokens: 120,
    retryProfile: "rare",
    cacheable: false,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 90,
    expectedCadence: "medium",
    suggestedCredits: 1,
  },
  {
    id: "corretor_eme.reply",
    module: "Corretor EME",
    feature: "Pre-atendimento no WhatsApp",
    capability: "lead.reply",
    route: "/api/whatsapp/webhook",
    file: "lib/eme-backend.ts",
    handler: "generateCorretorEmeReply",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Qualificacao inicial de leads recebidos no WhatsApp.",
    billableUnit: "request",
    avgInputTokens: 1000,
    avgOutputTokens: 240,
    retryProfile: "rare",
    cacheable: false,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 120,
    expectedCadence: "high",
    suggestedCredits: 1,
  },
  {
    id: "studio.instagram",
    module: "Studio IA",
    feature: "Campanha Instagram",
    capability: "campaign.structured_content",
    route: "/api/studio-ia/instagram",
    file: "lib/studio-ia-instagram.ts",
    handler: "generateInstagramCampaign",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Gera feed, story, carrossel, legenda, CTA e hashtags.",
    billableUnit: "request",
    avgInputTokens: 2100,
    avgOutputTokens: 900,
    retryProfile: "moderate",
    cacheable: true,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 16,
    expectedCadence: "medium",
    currentCreditActionKey: "studio_instagram_campaign",
    suggestedCredits: 10,
  },
  {
    id: "studio.buyers",
    module: "Studio IA",
    feature: "Campanha para compradores",
    capability: "studio.generateCampaign",
    route: "/api/studio-ia/buyers",
    file: "lib/studio-ia-buyers.ts",
    handler: "generateBuyerStrategy",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Gera estrategia, copy e timeline para captar compradores.",
    billableUnit: "request",
    avgInputTokens: 1700,
    avgOutputTokens: 720,
    retryProfile: "rare",
    cacheable: true,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 10,
    expectedCadence: "low",
    suggestedCredits: 5,
  },
  {
    id: "studio.instagram.xai",
    module: "Studio IA",
    feature: "Campanha Instagram",
    capability: "campaign.structured_content",
    route: "/api/studio-ia/instagram",
    file: "lib/studio-ia-instagram.ts",
    handler: "generateInstagramCampaignWithXAI",
    provider: "xai",
    model: "grok-4.5",
    description: "Gera o conteudo estruturado da campanha para o renderer existente do EME.",
    billableUnit: "request",
    avgInputTokens: 2100,
    avgOutputTokens: 900,
    retryProfile: "rare",
    cacheable: false,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 8,
    expectedCadence: "low",
    currentCreditActionKey: "studio_instagram_campaign",
    suggestedCredits: 10,
    notes: "Custo exato registrado por usage.cost_in_usd_ticks quando retornado pela xAI.",
  },
  {
    id: "studio.owners",
    module: "Studio IA",
    feature: "Campanha para proprietarios",
    capability: "studio.generateCampaign",
    route: "/api/studio-ia/owners",
    file: "lib/studio-ia-owners.ts",
    handler: "generateOwnerStrategy",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Gera captacao de proprietarios com anuncios, roteiros e CTA.",
    billableUnit: "request",
    avgInputTokens: 1800,
    avgOutputTokens: 860,
    retryProfile: "rare",
    cacheable: true,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 8,
    expectedCadence: "low",
    suggestedCredits: 5,
  },
  {
    id: "studio.sell_property",
    module: "Studio IA",
    feature: "Campanha de venda",
    capability: "studio.generateCampaign",
    route: "/api/studio-ia/sell-property",
    file: "lib/studio-ia-sell-property.ts",
    handler: "generateSellPropertyStrategy",
    provider: "openai",
    model: "gpt-5-mini",
    description: "Gera campanha de venda com foco comercial e criativos textuais.",
    billableUnit: "request",
    avgInputTokens: 1900,
    avgOutputTokens: 760,
    retryProfile: "rare",
    cacheable: true,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 10,
    expectedCadence: "low",
    suggestedCredits: 5,
  },
  {
    id: "studio.construction_image",
    module: "Studio IA",
    feature: "Transformacao de imagem",
    capability: "studio.generateImage",
    route: "/api/studio-ia/construction",
    file: "lib/studio-ia-construction.ts",
    handler: "generateConstructionImage",
    provider: "openai",
    model: "gpt-image-1",
    description: "Gera imagem comercial a partir de obra/construcao usando image_generation.",
    billableUnit: "image",
    avgInputTokens: 600,
    avgOutputTokens: 220,
    avgImages: 1,
    avgStorageMb: 1.4,
    retryProfile: "moderate",
    cacheable: false,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 8,
    expectedCadence: "low",
    suggestedCredits: 12,
    notes: "Custo principal concentrado na geracao de imagem.",
  },
  {
    id: "studio.video.preview",
    module: "Studio IA",
    feature: "Previa de video",
    capability: "studio.generateVideo",
    route: "/api/studio-ia/video",
    file: "lib/studio-ia-video.ts",
    handler: "createInitialStudioVideoJob",
    provider: "lumaai",
    model: "uni-1",
    description: "Gera preview da transformacao antes do video final.",
    billableUnit: "image",
    avgImages: 1,
    avgStorageMb: 1.8,
    retryProfile: "moderate",
    cacheable: false,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 6,
    expectedCadence: "low",
    currentCreditActionKey: "studio_ia_video_preview",
    suggestedCredits: 12,
  },
  {
    id: "studio.video.preview_regeneration",
    module: "Studio IA",
    feature: "Nova previa de video",
    capability: "studio.regenerate",
    route: "/api/studio-ia/video",
    file: "lib/studio-ia-video.ts",
    handler: "regenerateStudioVideoPreview",
    provider: "lumaai",
    model: "uni-1",
    description: "Regenera a previa aprovada antes de criar o video final.",
    billableUnit: "image",
    avgImages: 1,
    avgStorageMb: 1.8,
    retryProfile: "moderate",
    cacheable: false,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 2,
    expectedCadence: "low",
    currentCreditActionKey: "studio_ia_video_preview_regeneration",
    suggestedCredits: 12,
  },
  {
    id: "studio.video.final",
    module: "Studio IA",
    feature: "Video final",
    capability: "studio.generateVideo",
    route: "/api/studio-ia/video",
    file: "lib/studio-ia-video.ts",
    handler: "createApprovedStudioVideoAnimation",
    provider: "lumaai",
    model: "ray-3.2",
    description: "Gera video final comercial do imovel.",
    billableUnit: "video",
    avgVideos: 1,
    avgStorageMb: 9.5,
    retryProfile: "moderate",
    cacheable: false,
    criticity: "high",
    expectedUsagePerBrokerMonthly: 4,
    expectedCadence: "low",
    currentCreditActionKey: "studio_ia_video_final",
    suggestedCredits: 38,
    notes: "Fallback de custo aplicado a modelos legados ray-2/ray-flash-2.",
  },
  {
    id: "document.proposal_pdf",
    module: "Documentos",
    feature: "Proposta em PDF",
    capability: "proposal.download",
    route: "/api/brokers/documents/[id]/pdf-credit",
    file: "app/api/brokers/documents/[id]/pdf-credit/route.ts",
    handler: "POST",
    provider: "internal",
    model: "browser-print",
    description: "Geracao de PDF de proposta sem custo de API externa.",
    billableUnit: "document",
    retryProfile: "rare",
    cacheable: true,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 10,
    expectedCadence: "low",
    currentCreditActionKey: "generate_proposal_pdf",
    suggestedCredits: 1,
  },
  {
    id: "document.contract_pdf",
    module: "Contratos",
    feature: "Contrato em PDF",
    capability: "contract.download",
    route: "/api/brokers/contracts/[id]/pdf-credit",
    file: "app/api/brokers/contracts/[id]/pdf-credit/route.ts",
    handler: "POST",
    provider: "internal",
    model: "browser-print",
    description: "Geracao de PDF de contrato sem custo de API externa.",
    billableUnit: "document",
    retryProfile: "rare",
    cacheable: true,
    criticity: "medium",
    expectedUsagePerBrokerMonthly: 12,
    expectedCadence: "low",
    currentCreditActionKey: "generate_contract_pdf",
    suggestedCredits: 1,
  },
]

export function listAiOperationCatalog() {
  return [...catalog]
}

export function getAiOperationCatalogEntry(operationKey: string) {
  return catalog.find((entry) => entry.id === operationKey) ?? null
}
